### ISSUE TITLE
项目文件不存在

### ISSUE THREAD

**Issue by ztiandan** [nickliqian/darknet_captcha#1]
请问一下extend/generate_config_file.py这个文件在哪里？好像找不到
python3 extend/generate_config_file.py my_captcha 1
@nickliqian

**Comment by nickliqian** [comment]
@ztiandan 不好意思，我文件名称改了，这里更正一下`generate_config_file.py`的名称应该是`create_app_config.py`，已经在readme中更新了，谢谢提出。

**Comment by ztiandan** [comment]
好滴，多谢
