### ISSUE TITLE
请教个my_captcha.namesd的问题

### ISSUE THREAD

**Issue by ztiandan** [nickliqian/darknet_captcha#2]
请问一下我调用了下面的命令
python3 extend/create_app_config.py my_captcha 1
然后文件my_captcha.names的内容是class_0，请问这个内容是做什么用的呢？需要修改吗？谢谢
@nickliqian

**Comment by nickliqian** [comment]
my_captcha.names是识别出来之后结果的标签，可以修改为你指定的名称。

**Comment by ztiandan** [comment]
明白了，谢谢
