### ISSUE TITLE
较为复杂的文字点选能识别嘛？

### ISSUE THREAD

**Issue by tomorrow1pan** [nickliqian/darknet_captcha#5]
非常感谢您的项目分享，真的对我帮助很大，目前我需要破解文字点选验证码，文字有倾斜处理，也有繁体字，请问这种情况我们darknet识别效果好吗？是不是需要标注样本足够多？
![image10](https://user-images.githubusercontent.com/21055561/55300039-49066a80-5468-11e9-9140-8d7aca88dee1.JPG)
谢谢

**Comment by tomorrow1pan** [comment]
@nickliqian

**Comment by nickliqian** [comment]
@tomorrow1pan
是的，只要样本量足够然后标注的比较好的话，这样的图形是没有问题的！

**Comment by tomorrow1pan** [comment]
非常感谢
